version: "3.4"
name: vocdoni-demo

services:
  app:
    image: vocdoni/ui-scaffold
    build:
      context: https://github.com/vocdoni/ui-scaffold.git#local-demo-monkeypatch
      args:
        VOCDONI_ENVIRONMENT: local
    ports:
      - 8080:80
    depends_on:
      - voconed
      - census3

  explorer:
    image: ghcr.io/vocdoni/explorer-ui
    build:
      context: https://github.com/vocdoni/explorer-ui.git#local-demo-monkeypatch
      dockerfile: Dockerfile.static
      args:
        VOCDONI_ENVIRONMENT: local
    ports:
      - 127.0.0.1:8082:80
    depends_on:
      - voconed

  voconed:
    # pull main tag (instead of latest) to ensure we're testing against bleeding edge
    image: vocdoni/vocdoni-node:main
    entrypoint: /app/voconed
    environment:
      - VOCONED_PORT=9095
      - VOCONED_URLPATH=/v2
      - VOCONED_BLOCKPERIOD=5
      - VOCONED_BLOCKSIZE=2000
      - VOCONED_LOGLEVEL=debug
      - VOCONED_CHAINID=local
      - VOCONED_ENABLEFAUCETWITHAMOUNT=5000
      - VOCONED_TXCOSTS=2
      - VOCONED_SETTXCOSTS=true
    volumes:
      - voconed:/root
    ports:
      - 127.0.0.1:8081:9095
    sysctls:
      net.core.somaxconn: 8128
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "10"

  census3:
    image: ghcr.io/vocdoni/census3:stage
    ports:
      - 127.0.0.1:8083:7788
    sysctls:
      net.core.somaxconn: 8128
    volumes:
      - census3:/app/data
    command:
      - --web3Providers=https://eth-rpc.gateway.pokt.network/
      - --port=7788
      - --logLevel=debug
      - --connectKey=census3key
      - --dataDir=/app/data/census3

volumes:
  voconed: {}
  census3: {}
